name: "Sample React CI Pipeline / Workflow"

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: "Setup Node JS"
              uses: actions/setup-node@v7
              with:
                node-version: '26'

            - name: "Check node version"
              run: node --version
            
            - name: "Clone the repository"
              uses: actions/checkout@v7